name: release

on:
  - push

jobs:
  create-release-targets:
    runs-on: ubuntu-latest

    outputs:
      target_list: ${{ steps.create-target-list.outputs.list }}

    steps:
      - name: Checkout release environment
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Cretae target list
        id: create-target-list
        run: |
          list=`ruby ${GITHUB_WORKSPACE}/script/create_target_list.rb ${GITHUB_WORKSPACE}/release.yaml`
          echo $list
          echo "list=${list}" >> $GITHUB_OUTPUT

  release:
    needs: create-release-targets

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target_list: ${{fromJson(needs.create-release-targets.outputs.target_list)}}

    steps:
      - name: Checkout release environment
        uses: actions/checkout@v3

      - name: Setup target info
        run: |
          repository=$(echo ${{ matrix.target_list }} | cut -d ':' -f 1)
          version=$(echo ${{ matrix.target_list }} | cut -d ':' -f 2)
          echo "TARGET_REPOSITORY=${repository}" >> ${GITHUB_ENV}
          echo "TARGET_VERSION=${version}" >> ${GITHUB_ENV}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.RGGEN_APP_ID }}
          private_key: ${{ secrets.RGGEN_APP_KEY }}

      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: rggen/${{ env.TARGET_REPOSITORY }}
          path: release-target
          token: ${{ steps.generate_token.outputs.token }}

      - name: Bump version
        run: |
          cd release-target
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          bundle exec rake -f ${GITHUB_WORKSPACE}/Rakefile bump:set
          git push origin `git branch --show-current`
        env:
          VERSION: ${{ env.TARGET_VERSION }}
